# Generated by Django 4.0.3 on 2022-05-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
