version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: Backend.settings
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
    expose:
      - 8000
    entrypoint:
      - sh
      - config/entrypoint.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static: